### ISSUE TITLE
Traceback (most recent call last):   File "/usr/local/bin/nr7101-collector", line 6, in <module>     from collector.cli import cli

### ISSUE THREAD

**Issue by mo8Zomo0** [atorma/nr7101-influxdb-collector#1]
Hi, 

I tried to run it on a Debian 10 system, but I did not manage to do so.
The documentation is also not fully self explaining, like what is the collector
and how it works, like is it a daemon which runs the collection process and pipes it into
the db (possibly) or does it need to be run repeatably. 
Or there is a time value 5000 is this ms, so it would run every 5 sec?

Anyhow, when I try to run the collector it fails with a 

Traceback (most recent call last):
  File "/usr/local/bin/nr7101-collector", line 6, in <module>
    from collector.cli import cli

Details:
```
# pip3 install git+https://github.com/atorma/nr7101-influxdb-collector.git
Collecting git+https://github.com/atorma/nr7101-influxdb-collector.git
  Cloning https://github.com/atorma/nr7101-influxdb-collector.git to /tmp/pip-req-build-r8c58bv2
Requirement already satisfied (use --upgrade to upgrade): nr7101-influxdb-collector==2.2.3 from git+https://github.com/atorma/nr7101-influxdb-collector.git in /usr/local/lib/python3.7/dist-packages
Requirement already satisfied: influxdb-client==1.19.0 in /usr/local/lib/python3.7/dist-packages (from nr7101-influxdb-collector==2.2.3) (1.19.0)
Requirement already satisfied: nr7101@ git+https://github.com/pkorpine/nr7101.git@v1.3.0 from git+https://github.com/pkorpine/nr7101.git@v1.3.0 in /usr/local/lib/python3.7/dist-packages (from nr7101-influxdb-collector==2.2.3) (1.3.0)
Requirement already satisfied: ping3==2.9.1 in /usr/local/lib/python3.7/dist-packages (from nr7101-influxdb-collector==2.2.3) (2.9.1)
Requirement already satisfied: rx==3.2.0 in /usr/local/lib/python3.7/dist-packages (from nr7101-influxdb-collector==2.2.3) (3.2.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.7/dist-packages (from influxdb-client==1.19.0->nr7101-influxdb-collector==2.2.3) (2.8.2)
Requirement already satisfied: urllib3>=1.15.1 in /usr/lib/python3/dist-packages (from influxdb-client==1.19.0->nr7101-influxdb-collector==2.2.3) (1.24.1)
Requirement already satisfied: setuptools>=21.0.0 in /usr/lib/python3/dist-packages (from influxdb-client==1.19.0->nr7101-influxdb-collector==2.2.3) (40.8.0)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from influxdb-client==1.19.0->nr7101-influxdb-collector==2.2.3) (1.12.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/lib/python3/dist-packages (from influxdb-client==1.19.0->nr7101-influxdb-collector==2.2.3) (2018.8.24)
Requirement already satisfied: pytz>=2019.1 in /usr/local/lib/python3.7/dist-packages (from influxdb-client==1.19.0->nr7101-influxdb-collector==2.2.3) (2021.3)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from nr7101@ git+https://github.com/pkorpine/nr7101.git@v1.3.0->nr7101-influxdb-collector==2.2.3) (2.21.0)
Building wheels for collected packages: nr7101-influxdb-collector
  Running setup.py bdist_wheel for nr7101-influxdb-collector ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-6brj1qa6/wheels/92/d3/42/597b32fa3d630c67a106bce45a9edf21dfeeb0388d0602910b
Successfully built nr7101-influxdb-collector


# nr7101-collector  --config-file=/opt/nr7101-influxdb-collector/config.ini
Traceback (most recent call last):
  File "/usr/local/bin/nr7101-collector", line 6, in <module>
    from collector.cli import cli
  File "/usr/local/lib/python3.7/dist-packages/collector/cli.py", line 3, in <module>
    from .config import Config
  File "/usr/local/lib/python3.7/dist-packages/collector/config.py", line 7, in <module>
    class NR7101Config(typing.TypedDict):
AttributeError: module 'typing' has no attribute 'TypedDict'
```

**Comment by atorma** [comment]
Looks like the error `AttributeError: module 'typing' has no attribute 'TypedDict'` is because `TypedDict` was added in Python 3.8 and you are running Python 3.7. If that's the cause of the error, the README of this repo is wrong about the minimum Python version. I'll update it.

**Comment by atorma** [comment]
As for the collector, your idea of a daemon running the collection process is correct. The collector polls your NR7101 every 5000 ms, or whatever interval is in your configuration, and pipes the data into an InfluxDB. You start the collector as a background process, e.g. using systemd, and leave it to do its work. I'm running the collector in a Raspberry Pi.

**Comment by mo8Zomo0** [comment]
thx
