### ISSUE TITLE
Docker build: ModuleNotFoundError: No module named 'collector'

### ISSUE THREAD

**Issue by mo8Zomo0** [atorma/nr7101-influxdb-collector#2]
As a follow up to #1 
I must have been blind and did not notice the Dockerfile for the collector (which uses python 3.9.6 as it looks)
It also does not seem to be mentioned in the Readme.

Sadly a _docker build ._ fails for me as well:

```
/opt/nr7101-influxdb-collector# docker build .
Sending build context to Docker daemon  185.9kB
Step 1/11 : FROM python:3.9.6-buster
3.9.6-buster: Pulling from library/python
1cfaf5c6f756: Pull complete 
c4099a935a96: Pull complete 
f6e2960d8365: Pull complete 
dffd4e638592: Pull complete 
2ce46ad6f244: Pull complete 
9191ad4801e9: Pull complete 
175014bfd612: Pull complete 
b12ae324d7e6: Pull complete 
0d353f58212b: Pull complete 
Digest: sha256:f1cfaacc24b7c8e344aa0169201f4f001b6776f7d771573f48acad6f05d8fcd2
Status: Downloaded newer image for python:3.9.6-buster
 ---> c26b8ed5168c
Step 2/11 : RUN useradd --create-home appuser
 ---> Running in 6796df560908
Removing intermediate container 6796df560908
 ---> 0c2e95113d1b
Step 3/11 : USER appuser
 ---> Running in e61888382946
Removing intermediate container e61888382946
 ---> b0597842aa8b
Step 4/11 : RUN python3 -m pip install --upgrade pip
 ---> Running in c0eb1c6f70cd
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.2.4)
Removing intermediate container c0eb1c6f70cd
 ---> 07961c5e30f6
Step 5/11 : RUN mkdir -p /home/appuser/app
 ---> Running in 04de187e3c83
Removing intermediate container 04de187e3c83
 ---> 679d8e7ad8b9
Step 6/11 : WORKDIR /home/appuser/app
 ---> Running in 91740b66b31d
Removing intermediate container 91740b66b31d
 ---> 48d62305cde0
Step 7/11 : USER appuser
 ---> Running in 0ccf9e6c4fd2
Removing intermediate container 0ccf9e6c4fd2
 ---> e0142cd13b14
Step 8/11 : COPY setup.py .
 ---> 8a56161ac0ff
Step 9/11 : RUN pip install . --no-cache-dir
 ---> Running in 31d3b85ea0df
Defaulting to user installation because normal site-packages is not writeable
Processing /home/appuser/app
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rqkdq7xl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rqkdq7xl/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u39wufuh
         cwd: /tmp/pip-req-build-rqkdq7xl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rqkdq7xl/setup.py", line 2, in <module>
        from collector.version import __version__
    ModuleNotFoundError: No module named 'collector'
    ----------------------------------------
WARNING: Discarding file:///home/appuser/app. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install . --no-cache-dir' returned a non-zero code: 1


# docker -v
Docker version 20.10.9, build c2ea9bc

# cat /etc/issue
Debian GNU/Linux 10 \n \l
```

**Comment by atorma** [comment]
Looks like I committed the Dockerfile by accident in the initial commit. I wasn't using it myself and it was broken, too. However, I made some fixes now and updated the readme. Hope it works for you, I haven't had the time to do proper testing. At least it seems to get a connection to my NR7101 and attempts to connect to an InfluxDB URL.

**Comment by mo8Zomo0** [comment]
seems to work here as well, at least it shows some values in grafana ;-)

thx
